quarkus.profile=dev
quarkus.rest-client.via-cep.url=https://viacep.com.br/
quarkus.rest-client.via-cep.connectionTimeout=1000
taxas.valor-simulado=1
quarkus.http.port=9000

# Usa Postgres
%dev.quarkus.datasource.db-kind=postgresql

# Garante que NADA seja exposto por acidente
quarkus.http.auth.permission.authenticated-all.paths=/*
quarkus.http.auth.permission.authenticated-all.policy=authenticated

quarkus.http.auth.permission.public.paths=/q/health/*
quarkus.http.auth.permission.public.policy=permit

#Usuarios
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.vini=123
quarkus.security.users.embedded.users.outro_user=456

#Roles
quarkus.security.users.embedded.roles.vini=Gerente
quarkus.security.users.embedded.roles.outro_user=Usuario

# Usa H2 em memória para facilitar o desenvolvimento
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:clientes
%test.quarkus.hibernate-orm.database.generation=drop-and-create