quarkus.profile=h2
quarkus.rest-client.via-cep.url=https://viacep.com.br/
quarkus.rest-client.via-cep.connectionTimeout=1000
taxas.valor-simulado=1
quarkus.http.port=9000

# Usa Postgres
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clientes
%dev.quarkus.datasource.username=admin
%dev.quarkus.datasource.password=admin
%dev.quarkus.hibernate-orm.database.generation=update

# Usa H2 em memória para facilitar o desenvolvimento
%h2.quarkus.datasource.db-kind=h2
%h2.quarkus.datasource.jdbc.url=jdbc:h2:mem:clientes
%h2.quarkus.hibernate-orm.database.generation=drop-and-create